[mic]
# driver = "coreaudio"
driver = "alsa"
device_name = "hw:RASPZX16ch"
# device_name = "hw:ArrayUAC10"
device_id = 0
sample_rate = 16000
period = 32
n_channel = 6

[speaker]
use_alsa_out = false
device_name = "plughw:Device"
sample_rate = 16000
period = 32
n_period = 2
n_channel = 1

[audio_connection]
# connect_mic_speaker = true
connect_mic_speaker = false
mic_idx = 0
speaker_idx = 0

[tcp_sender]
listen_port = 7998
max_clients = 100
header_len = 12
sample_per_packet = 160

[tcp_receiver]
host = "none"
port = 4000
header_len = 16
n_channel = 1
sample_per_packet = 160