[general]
sample_rate = 16000
period = 32
n_period = 3
sample_per_packet = 32
device_id = 0

[[capture_device]]
device_name = "hw:RASPZX16ch"
n_channel = 16

[playback]
device_name = "plughw:Device"
n_channel = 1

[sender]
protocol = "udp"
listen_port = 7998
max_clients = 100

[receiver]
protocol = "udp"
host = "none"
port = 4000
n_channel = 1
