[mic]
# driver = "coreaudio"
driver = "alsa"
device_name = "hw:RASPZX16ch"
device_id = 0
sample_rate = 16000
period = 64
n_channel = 16

[speaker]
device_name = "plughw:Device"
sample_rate = 16000
period = 64
n_period = 4
n_channel = 1

[audio_connection]
# connect_mic_speaker = true
connect_mic_speaker = false
mic_idx = 0
speaker_idx = 0

[tcp]
listen_port = 7998
max_clients = 10
header_len = 12
sample_per_packet = 160